name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Generate config.js from template
      run: |
        echo "Generating config.js..."
        cp config.template.js config.js
        sed -i "s|__GOOGLE_CLIENT_ID__|${{ secrets.GOOGLE_CLIENT_ID }}|g" config.js
        sed -i "s|__GOOGLE_API_KEY__|${{ secrets.GOOGLE_API_KEY }}|g" config.js
        sed -i "s|__GOOGLE_SHEET_ID__|${{ secrets.GOOGLE_SHEET_ID }}|g" config.js
        mkdir build
        cp index.html config.js styles.css auth.js script.js build/
        echo "✅ Generated and copied all files to build/"

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        branch: gh-pages
        folder: build
